scrape_configs:
  - job_name: "dgraph"
    metrics_path: "/debug/prometheus_metrics"
    scrape_interval: "2s"
    static_configs:
    - targets:
      - zero:6080 
      - alpha:8080
  - job_name: "cadvisor"
    scrape_interval: "5s"
    static_configs:
    - targets:
      - cadvisor:8080
