apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    tier: frontend-pod
  spec:
    replicas: 1
    container:
      - name: frontend:latest
      - image: enatrox/cloud-project-frontend:latest
      env:
      - name: ENABLE_AUTH
        value: false
      - name: ISSUER_URL
        vaule: http://localhost:8087/auth/realms/SpringBootKeycloak
      - name: REDIR_URL
        value: http://localhost:80/
      - name: CLIENT_ID
        value: login-app
      - name: DB_URL
        value: http://localhost:8080
      ports:
        - port: 80
          targetPort: 80
          protocol: TCP
          name: http
  ---

