server:
  port: 8081
keycloak:
  auth-server-url: "http://localhost:8080/auth"
  resource: "login-app"
  realm: "SpringBootKeycloak"
  ssl-required: "external"
  public-client: true
  bearer-only: true